config/routes.rb
Rails.application.routes.draw do
  get 'public/homepage'

  get 'public/about'

  get 'public/projects'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def homepage
  end

  def about
    content =
    [
      'send a message',
      'send'
    ]

    @content = { message: '', name: '' }

    render :locals => { content: content }
  end

  def projects
  	content = 
  	{
  		projects: [
  			{
  				title: 'FreelancerHub',
  				technologies: 'Ruby, Rails'
  			},
  			{
  				title: 'LayoutsAndStyles',
  				technologies: 'Ruby, Rails, SASS'
  			},
  			{
  				title: 'Show me the Knowledge',
  				technologies: 'C++, Git'
  			},
  			{
  				title: 'Build the Beast',
  				technologies: 'C++, Git'
  			},
  			{
  				title: 'Blackboard Basics',
  				technologies: 'Ruby, Rails, MySql, SASS, Git'
  			},
  			{
  				title: 'Andrew\'s Worst Nightmare',
  				technologies: 'Java'
  			},
  			{
  				title: 'Haya',
  				technologies: 'Ruby, Rails, C#, Xamarin, MySql, Git'
  			}
  		]
  	}

  	render :locals => { content: content }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LayoutsAndHelpers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <ul>
    <li><%= link_to 'Home', public_homepage_path %></li>
    <li><%= link_to 'About', public_about_path %></li>
    <li><%= link_to 'Projects', public_projects_path %></li>
  </ul>
</footer>